import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

// Connecting to The Office API 
const defaultEndpoint = 'https://officeapi.dev/api/quotes/random'

export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint);
  const data = await res.json();
  return {
    props: {
      data
    }
  }
}

export default function Home({ data }) {
  const { results = [] } = data;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            "It's like having Austin in your pocket!"
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By Sam{' '}
              {/* <Image
                // src="/vercel.svg"
                // alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              /> */}
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            src="/prison_mike.png"
            alt="Prison Mike"
            width={250}
            height={200}
            priority
          />
        </div>

        <div id="quote-container">
        <div id="quote-area">
        <h1 id="quote-content">"I feel like all my kids grew up, and then they married each other. It’s every parent’s dream."</h1>
          <span class="name-container">
          <h1 id="first-name">Michael</h1>
          
          <h1 id="last-name">Scott</h1>
          </span>
          <br></br>
          <br></br>
          </div>
          <button href="#">Generate Quote</button>
        </div>
       
      </main>
    </>
  )
}
