import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React from 'react'
const inter = Inter({ subsets: ['latin'] })
import { useState, useEffect } from 'react'
import Quote from '../components/Quote'

// Connecting to The Office API 
// const defaultEndpoint = 'https://officeapi.dev/api/quotes/random'

// export async function getServerSideProps() {
//   const res = await fetch(defaultEndpoint);
//   const data = await res.json();
//   return {
//     props: {
//       data
//     }
//   }
// }

// Refresh Quote Function 
function handleClick() {
  console.log("button clicked")
  window.location.reload(true)
}


// export default function Home({ data }) {
export default function Home() {

  // console.log(data)
  // console.log(data.data.character.firstname)

  //Likes Function on Footer
  const [likes, setLikes] = React.useState(0);
  function clickLike() {
    setLikes(likes + 1);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            "It's like having Austin in your pocket!"
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By Sam{' '}
              {/* <Image
                // src="/vercel.svg"
                // alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              /> */}
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            src="/prison_mike.png"
            alt="Prison Mike"
            width={250}
            height={200}
            priority
          />
        </div>

        <div>
          <h1>Random Quote Generator</h1>
          <Quote />
         </div>

        {/* <div id="quote-container">
        <div id="quote-area">
        <h1 id="quote-content">"{ data.data.content}"</h1>
          <span className="name-container">
          <h1 id="first-name">{ data.data.character.firstname }</h1>
          
          <h1 id="last-name">{ data.data.character.lastname }</h1>
          </span>
          <br></br>
          <br></br>
          </div>
          <button onClick={handleClick}>Generate Quote</button>
        </div> */}
       
      </main>
      <footer>
        <h3>Like this page? Give us a like!</h3>
      <button onClick={clickLike}>Like This Page</button>
      <p>Likes: {likes} </p>
      </footer>
    </>
  )
}
